listSongRecommend_Vpop = [
  {
    name: "Đế vương",
    author: "Đình Dũng",
    duration: "04:22",
    image: "./img/song-img/vpop/song-1.jpg",
    path: "./song-mp3/vpop/song-1.mp3",
  },
  {
    name: "#Catena",
    author: "Tóc Tiên, Tourliver",
    duration: "04:29",
    image: "./img/song-img/vpop/song-2.jpg",
    path: "./song-mp3/vpop/song-2.mp3",
  },
  {
    name: "Anh ơi ở lại",
    author: "ChiPu",
    duration: "05:41",
    image: "./img/song-img/vpop/song-3.jpg",
    path: "./song-mp3/vpop/song-3.mp3",
  },
  {
    name: "Ái nộ",
    author: "Masew, Khôi Vũ",
    duration: "03:20",
    image: "./img/song-img/vpop/song-4.jpg",
    path: "./song-mp3/vpop/song-4.mp3",
  },
  {
    name: "Thê lương",
    author: "Phúc Chinh",
    duration: "05:13",
    image: "./img/song-img/vpop/song-5.jpg",
    path: "./song-mp3/vpop/song-5.mp3",
  },
  {
    name: "SG đau lòng quá",
    author: "Hứa Kim Tuyền, Hoàng Duyên",
    duration: "05:08",
    image: "./img/song-img/vpop/song-6.jpg",
    path: "./song-mp3/vpop/song-6.mp3",
  },
  {
    name: "Cưới thôi",
    author: "Masiu, Masew",
    duration: "03:01",
    image: "./img/song-img/vpop/song-7.jpg",
    path: "./song-mp3/vpop/song-7.mp3",
  },
  {
    name: "Thức giấc",
    author: "DaLAB",
    duration: "04:29",
    image: "./img/song-img/vpop/song-8.jpg",
    path: "./song-mp3/vpop/song-8.mp3",
  },
  {
    name: "Đi về nhà",
    author: "Đen, Justa Tee ",
    duration: "03:25",
    image: "./img/song-img/vpop/song-9.jpg",
    path: "./song-mp3/vpop/song-9.mp3",
  },
  {
    name: "Gieo quẻ",
    author: "Đen, Hoàng Thùy Linh",
    duration: "04:19",
    image: "./img/song-img/vpop/song-10.jpg",
    path: "./song-mp3/vpop/song-10.mp3",
  },
  {
    name: "Mang tiền về cho mẹ",
    author: "Đen",
    duration: "06:41",
    image: "./img/song-img/vpop/song-11.jpg",
    path: "./song-mp3/vpop/song-11.mp3",
  },
  {
    name: "Rap chậm thôi",
    author: "RPT MCK, RPT Jinn, RZ Ma$",
    duration: "04:09",
    image: "./img/song-img/vpop/song-12.jpg",
    path: "./song-mp3/vpop/song-12.mp3",
  },
  {
    name: "Thủ đô Cypher",
    author: "RPT MCK, Low G,...",
    duration: "02:54",
    image: "./img/song-img/vpop/song-13.jpg",
    path: "./song-mp3/vpop/song-13.mp3",
  },
  {
    name: "Tháng năm",
    author: "SooBin",
    duration: "03:56",
    image: "./img/song-img/vpop/song-14.jpg",
    path: "./song-mp3/vpop/song-14.mp3",
  },
  {
    name: "Chiều hôm ấy",
    author: "JayKii",
    duration: "05:17",
    image: "./img/song-img/vpop/song-16.jpg",
    path: "./song-mp3/vpop/song-16.mp3",
  },
  {
    name: "Nàng thơ",
    author: "Hoàng Dũng",
    duration: "05:21",
    image: "./img/song-img/vpop/song-17.jpg",
    path: "./song-mp3/vpop/song-17.mp3",
  },
  {
    name: "Dân chơi xóm",
    author: "RPT MCK, Justa Tee",
    duration: "03:30",
    image: "./img/song-img/vpop/song-18.jpg",
    path: "./song-mp3/vpop/song-18.mp3",
  },
];

listSongRecommend_USUK = [
  {
    name: "Memories",
    author: "Maroon 5",
    duration: "03:15",
    image: "./img/song-img/us-uk/song-1.jpg",
    path: "./song-mp3/us-uk/song-1.mp3",
  },
  {
    name: "On my way",
    author: "Alan Walker, Sabrina,..",
    duration: "03:36",
    image: "./img/song-img/us-uk/song-2.jpg",
    path: "./song-mp3/us-uk/song-2.mp3",
  },
  {
    name: "Señorita",
    author: "Shawn Mendes, Camila,..",
    duration: "03:25",
    image: "./img/song-img/us-uk/song-3.jpg",
    path: "./song-mp3/us-uk/song-3.mp3",
  },
  {
    name: "Im Not Her",
    author: "Clara Mae",
    duration: "03:12",
    image: "./img/song-img/us-uk/song-4.jpg",
    path: "./song-mp3/us-uk/song-4.mp3",
  },
  {
    name: "Someone You Loved ",
    author: "Lewis Capaldi",
    duration: "03:01",
    image: "./img/song-img/us-uk/song-5.jpg",
    path: "./song-mp3/us-uk/song-5.mp3",
  },
  {
    name: "Dont Wanna Know",
    author: "Maroon 5",
    duration: "06:18",
    image: "./img/song-img/us-uk/song-6.jpg",
    path: "./song-mp3/us-uk/song-6.mp3",
  },
  {
    name: "Blinding Lights",
    author: "- The Weeknd",
    duration: "03:23",
    image: "./img/song-img/us-uk/song-7.jpg",
    path: "./song-mp3/us-uk/song-7.mp3",
  },
  {
    name: "Dusk Till Dawn",
    author: "ZAYN  Sia",
    duration: "03:55",
    image: "./img/song-img/us-uk/song-8.jpg",
    path: "./song-mp3/us-uk/song-8.mp3",
  },
  {
    name: "Cheap Thrills",
    author: "Sia",
    duration: "04:05",
    image: "./img/song-img/us-uk/song-9.jpg",
    path: "./song-mp3/us-uk/song-9.mp3",
  },
  {
    name: "Treat You Better",
    author: "Shawn Mendes",
    duration: "04:16",
    image: "./img/song-img/us-uk/song-10.jpg",
    path: "./song-mp3/us-uk/song-10.mp3",
  },
  {
    name: "Shape of You",
    author: "Ed Sheeran",
    duration: "04:23",
    image: "./img/song-img/us-uk/song-11.jpg",
    path: "./song-mp3/us-uk/song-11.mp3",
  },
  {
    name: "Hello",
    author: "Adele",
    duration: "06:06",
    image: "./img/song-img/us-uk/song-12.jpg",
    path: "./song-mp3/us-uk/song-12.mp3",
  },
  {
    name: "Yummy",
    author: "Justin Bieber",
    duration: "03:50",
    image: "./img/song-img/us-uk/song-13.jpg",
    path: "./song-mp3/us-uk/song-13.mp3",
  },
  {
    name: "Send My Love",
    author: "Adele",
    duration: "02:22",
    image: "./img/song-img/us-uk/song-14.jpg",
    path: "./song-mp3/us-uk/song-14.mp3",
  },
  {
    name: "FRIENDS",
    author: "Marshmello, AnneMarie",
    duration: "03:51",
    image: "./img/song-img/us-uk/song-15.jpg",
    path: "./song-mp3/us-uk/song-15.mp3",
  },
];
